service: dynamodbtrigger
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  lambdaHashingVersion: 20201221

  environment:
    TEST_TABLE_NAME: ${self:custom.TestTable.name}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:Query
        - dynamodb:DescribeStream
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
      Resource:
        - ${self:custom.TestTable.arn}

functions:
  graphql:
    handler: handler.handler
    events:
      - http:
          method: GET
          path: /test
      - stream:
          type: dynamodb
          batchSize: 20
          startingPosition: LATEST
          arn:
            Fn::GetAtt:
              - TestTable
              - StreamArn

resources:
  Resources:
    TestTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TestTable-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

custom:
  TestTable:
    name: !Ref TestTable
    arn: !GetAtt TestTable.Arn
